name: Python Application CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Download model files
        run: |
          mkdir -p models
          wget https://raw.githubusercontent.com/sidhartthhhhh/credit-card-fraud-detection/master/models/lgbm_fraud_detector.pkl -O models/lgbm_fraud_detector.pkl
          wget https://raw.githubusercontent.com/sidhartthhhhh/credit-card-fraud-detection/master/models/robust_scaler.pkl -O models/robust_scaler.pkl

          
      - name: Run tests
        run: |
          pytest
